apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: smart-factory-db.cjwquuemwozd.us-east-2.rds.amazonaws.com:5432
    database: postgres
    user: postgres
    uid: postgres-smartfactory
    secureJsonData:
      password: 93jJmLkpW8Fa49G
    jsonData:
      sslmode: 'require'
      postgresVersion: 15
